// Generated by CoffeeScript 1.7.1
(function() {
  var B, M, jade, tpl;

  jade = require("jade");

  B = require('backbone');

  M = require('backbone.marionette');

  tpl = require('./tpl');

  module.exports = {
    register: function() {
      return console.log('register');
    },
    login: function() {
      console.log('login');
      return $('#contain').append($(tpl.login()));
    },
    "default": function() {
      console.log(tpl['404'](), tpl.base());
      return console.log('default');
    }
  };

}).call(this);

//# sourceMappingURL=handler.map
