// Generated by CoffeeScript 1.7.1
(function() {
  var B, M, app, handler, router, tpl;

  require('zepto');

  B = require('backbone');

  B.$ = $;

  M = require('backbone.marionette');

  handler = require('./handler');

  tpl = require('./tpl');

  router = M.AppRouter.extend({
    controller: handler,
    appRoutes: {
      'login': 'login',
      'register': 'register',
      '*default': 'default'
    }
  });

  app = new M.Application();

  app.on('start', function() {
    var R;
    R = new router();
    B.history.start({
      pushState: true,
      root: '/'
    });
    $('#wrap').append($(tpl.base()));
    return $(document).on('click', 'a[href^="/"]', function(e) {
      e.preventDefault();
      return R.navigate($(e.currentTarget).attr('href').substr(1), {
        trigger: true
      });
    });
  });

  module.exports = app;

}).call(this);

//# sourceMappingURL=index.map
